# Generated by Django 5.0.6 on 2024-07-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Febati_APP_85', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagenProducto',
            new_name='Imagen_Producto',
        ),
    ]
