# Generated by Django 5.0.6 on 2024-06-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Febati_APP_85', '0001_initial'),
    ]

    


    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('Correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('Usuario', models.CharField(blank=True, max_length=14, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PRODUCTO',
        ),
    ]
