# Generated by Django 5.0.6 on 2024-07-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Febati_APP_85', '0002_usuario_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
